# Generated by Django 3.0.5 on 2021-06-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.TextField(max_length=50)),
                ('lName', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=20)),
                ('hasRequest', models.BooleanField(default=False)),
                ('amntToBorrow', models.IntegerField(default=0)),
                ('reasonToBorrow', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.TextField(max_length=50)),
                ('lName', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=20)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAmount', models.IntegerField()),
                ('totalLoanAmount', models.IntegerField()),
                ('loanPeriod', models.DurationField()),
                ('annualInterestRate', models.FloatField()),
                ('startDate', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Funded', 'Funded'), ('Completed', 'Completed')], max_length=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenme.Borrower')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenme.Investor')),
            ],
        ),
    ]
