# Generated by Django 3.0.5 on 2021-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='fName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='lName',
            field=models.CharField(max_length=50),
        ),
    ]
